type GradleConfig = { modResults: { contents: string } };
type GradleMod = (config: GradleConfig) => GradleConfig;

/**
 * `jest.mock`'s factory may only close over names beginning with `mock`, hence
 * the prefix. It collects the mod the plugin registers so the test can run the
 * Gradle transform directly, without a prebuild.
 */
const mockRegisteredMods: GradleMod[] = [];

jest.mock('expo/config-plugins', () => ({
  withAppBuildGradle: (config: unknown, mod: GradleMod) => {
    mockRegisteredMods.push(mod);

    return config;
  },
}));

const withAndroidReleaseSigning = jest.requireActual(
  '../../../../plugins/with-android-release-signing.js'
) as (config: unknown) => unknown;

/**
 * The three anchors the plugin patches, verbatim from the Expo SDK 57 Android
 * template, with the rest elided. Held here rather than read from
 * `android/app/build.gradle` because that directory is gitignored and only
 * exists after a prebuild - a test that read it would pass on a developer's
 * machine and be skipped in CI, which is the opposite of what this guards.
 */
const TEMPLATE_BUILD_GRADLE = `apply plugin: "com.android.application"

def jscFlavor = 'io.github.react-native-community:jsc-android:2026004.+'

android {
    ndkVersion rootProject.ext.ndkVersion

    namespace 'com.anonymous.mobileappecc'
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableMinifyInReleaseBuilds
        }
    }
}
`;

function applyPlugin(contents: string): string {
  mockRegisteredMods.length = 0;
  withAndroidReleaseSigning({});

  const [mod] = mockRegisteredMods;

  return mod({ modResults: { contents } }).modResults.contents;
}

describe('with-android-release-signing', () => {
  // The defect this plugin exists for: `android/` is regenerated by every
  // prebuild, so the template's "release is signed with the debug key" is
  // restored every time unless something re-applies the fix.
  it('stops the release build type from being hard-wired to the debug key', () => {
    // Arrange / Act
    const patched = applyPlugin(TEMPLATE_BUILD_GRADLE);

    // Assert
    expect(patched).not.toContain(`            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`);
    expect(patched).toContain(
      'signingConfig eccReleaseSigningConfigured ? signingConfigs.release : signingConfigs.debug'
    );
  });

  // The deliberate half of the design. The internal LAN demo APK and the
  // offline demo APK are both `assembleRelease` on machines with no release
  // keystore, and the Google OAuth Android client in use today is registered
  // against the debug keystore's SHA-1. Hard-failing would break both.
  it('keeps debug signing as the fallback rather than failing the build', () => {
    // Arrange / Act
    const patched = applyPlugin(TEMPLATE_BUILD_GRADLE);

    // Assert
    expect(patched).toContain('signingConfigs.debug');
    expect(patched).toContain("keyAlias 'androiddebugkey'");
  });

  // Credentials must be resolved by Gradle on the build machine, never baked
  // into a generated file that a `git status` could tempt someone to stage.
  it('emits credential lookups, not credentials', () => {
    // Arrange / Act
    const patched = applyPlugin(TEMPLATE_BUILD_GRADLE);

    // Assert
    expect(patched).toContain("new File(rootProject.projectDir.parentFile, 'keystore.properties')");
    expect(patched).toContain("System.getenv('ANDROID_RELEASE_STORE_PASSWORD')");
  });

  // `expo prebuild` without `--clean` re-runs the mods over an android/ that
  // was already patched. The anchors only exist in the pristine template, so
  // without the marker check the second prebuild would throw.
  it('is a no-op when it has already patched the file', () => {
    // Arrange
    const patchedOnce = applyPlugin(TEMPLATE_BUILD_GRADLE);

    // Act
    const patchedTwice = applyPlugin(patchedOnce);

    // Assert
    expect(patchedTwice).toBe(patchedOnce);
  });

  // Silently skipping on an unrecognised template is the one failure mode that
  // would ship a debug-signed artifact while reporting success.
  it('throws rather than skipping when the template no longer matches', () => {
    // Arrange
    const drifted = TEMPLATE_BUILD_GRADLE.replace(
      '            signingConfig signingConfigs.debug\n            minifyEnabled',
      '            signingConfig signingConfigs.release\n            minifyEnabled'
    );

    // Act / Assert
    expect(() => applyPlugin(drifted)).toThrow(/does not match the Expo template/);
  });
});
